version: '3.8'
services:
  db-key-manager:
    container_name: db-key-manager
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'keyManager'
      MYSQL_USER: 'blueDragons'
      MYSQL_PASSWORD: 'azul0jcuro'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data_key_manager:/var/lib/mysql
volumes:
  data_key_manager:
